name: baadd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.0.1
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - adversarial-robustness-toolbox
    - pandas
    - matplotlib
    - pyyaml