name: baadd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.0.1
  - cudatoolkit=11.3.1
  - pip:
    - torch
    - torchvision
    - torchaudio
    - adversarial-robustness-toolbox